In [1]:
#auto-reload external modules

%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/home/jovyan/work/data/raw/beer_reviews.csv')

In [4]:
df.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [5]:
df.shape

(1586614, 13)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1586614 non-null int64
brewery_name          1586599 non-null object
review_time           1586614 non-null int64
review_overall        1586614 non-null float64
review_aroma          1586614 non-null float64
review_appearance     1586614 non-null float64
review_profilename    1586266 non-null object
beer_style            1586614 non-null object
review_palate         1586614 non-null float64
review_taste          1586614 non-null float64
beer_name             1586614 non-null object
beer_abv              1518829 non-null float64
beer_beerid           1586614 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 157.4+ MB

In [7]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.518829e+06,1.586614e+06
mean,3.130099e+03,1.224089e+09,3.815581e+00,3.735636e+00,3.841642e+00,3.743701e+00,3.792860e+00,7.042387e+00,2.171279e+04
std,5.578104e+03,7.654427e+07,7.206219e-01,6.976167e-01,6.160928e-01,6.822184e-01,7.319696e-01,2.322526e+00,2.181834e+04
min,1.000000e+00,8.406720e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,3.000000e+00
25%,1.430000e+02,1.173224e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.717000e+03
50%,4.290000e+02,1.239203e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.390600e+04
75%,2.372000e+03,1.288568e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.944100e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731700e+04

In [8]:
duplicate = df.duplicated()
print(duplicate.sum())

0

In [9]:
df.isnull().any().sum()

3

In [10]:
df.isnull().sum()

brewery_id                0
brewery_name             15
review_time               0
review_overall            0
review_aroma              0
review_appearance         0
review_profilename      348
beer_style                0
review_palate             0
review_taste              0
beer_name                 0
beer_abv              67785
beer_beerid               0
dtype: int64

In [11]:
#df = df.fillna(0)
#print(df['beer_name'].value_counts())

In [12]:
#df.isnull().sum()
print(df['brewery_name'].value_counts())

Boston Beer Company (Samuel Adams)                 39444
Dogfish Head Brewery                               33839
Stone Brewing Co.                                  33066
Sierra Nevada Brewing Co.                          28751
Bell's Brewery, Inc.                               25191
                                                   ...
Brauerei Gold Ochsen GmbH                              1
Atna Bryggeri                                          1
OOO UK Pokrovskaya                                     1
Integrated Bottling Solutions                          1
Shinshu Toumi City Promotion Public Corporation        1
Name: brewery_name, Length: 5742, dtype: int64

In [13]:
df_cleaned = df.copy()

In [14]:
df_cleaned.drop('brewery_id', axis = 1, inplace = True)

In [15]:
df_cleaned.drop('beer_beerid', axis = 1, inplace = True)

In [16]:
df_cleaned.drop('beer_name', axis = 1, inplace = True)

In [17]:
df_cleaned.drop('beer_abv', axis = 1, inplace = True)

In [18]:
df_cleaned.drop('review_profilename', axis = 1, inplace = True)

In [19]:
target_col = 'beer_style'

In [70]:
cat_cols = ['brewery_name']

In [71]:
num_cols = list(set(df_cleaned.columns) - (set(cat_cols) | set([target_col])))

In [72]:
num_cols

['review_appearance',
 'review_overall',
 'review_palate',
 'review_taste',
 'review_time',
 'review_aroma']

In [73]:
cat_cols

['brewery_name']

In [74]:
df_cleaned

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,1234817823,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,Vecchio Birraio,1235915097,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,Vecchio Birraio,1235916604,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,Vecchio Birraio,1234725145,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,Caldera Brewing Company,1293735206,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...
1586609,The Defiant Brewing Company,1162684892,5.000000,4.000000,3.500000,Pumpkin Ale,4.000000,4.000000
1586610,The Defiant Brewing Company,1161048566,4.000000,5.000000,2.500000,Pumpkin Ale,2.000000,4.000000
1586611,The Defiant Brewing Company,1160702513,4.500000,3.500000,3.000000,Pumpkin Ale,3.500000,4.000000
1586612,The Defiant Brewing Company,1160023044,4.000000,4.500000,4.500000,Pumpkin Ale,4.500000,4.500000
1586613,The Defiant Brewing Company,1160005319,5.000000,4.500000,4.500000,Pumpkin Ale,4.500000,4.500000

In [75]:
def subset_x_y(target, features, start_index:int, end_index:int):
    """Keep only the rows for X and y sets from the specified indexes

    Parameters
    ----------
    target : pd.DataFrame
        Dataframe containing the target
    features : pd.DataFrame
        Dataframe containing all features
    features : int
        Index of the starting observation
    features : int
        Index of the ending observation

    Returns
    -------
    pd.DataFrame
        Subsetted Pandas dataframe containing the target
    pd.DataFrame
        Subsetted Pandas dataframe containing all features
    """
    
    return features[start_index:end_index], target[start_index:end_index]

In [76]:
#target = df_cleaned.pop('beer_style')

In [77]:
df_cleaned

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,1234817823,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,Vecchio Birraio,1235915097,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,Vecchio Birraio,1235916604,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,Vecchio Birraio,1234725145,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,Caldera Brewing Company,1293735206,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...
1586609,The Defiant Brewing Company,1162684892,5.000000,4.000000,3.500000,Pumpkin Ale,4.000000,4.000000
1586610,The Defiant Brewing Company,1161048566,4.000000,5.000000,2.500000,Pumpkin Ale,2.000000,4.000000
1586611,The Defiant Brewing Company,1160702513,4.500000,3.500000,3.000000,Pumpkin Ale,3.500000,4.000000
1586612,The Defiant Brewing Company,1160023044,4.000000,4.500000,4.500000,Pumpkin Ale,4.500000,4.500000
1586613,The Defiant Brewing Company,1160005319,5.000000,4.500000,4.500000,Pumpkin Ale,4.500000,4.500000

In [78]:
#y_main, X_main = subset_x_y(df_cleaned, target, 0,1000000 )

y_main, X_main = subset_x_y(df_cleaned, df_cleaned['beer_style'], 0, 1000000)

In [79]:
from src.data.sets import split_sets_random, save_sets

In [80]:
X_main

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,1234817823,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,Vecchio Birraio,1235915097,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,Vecchio Birraio,1235916604,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,Vecchio Birraio,1234725145,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,Caldera Brewing Company,1293735206,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...
999995,3 Ravens Brewing,1304226603,-0.476617,-1.126700,1.062766,Altbier,-0.404538,-1.151941
999996,3 Ravens Brewing,1301565814,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-1.855677
999997,3 Ravens Brewing,1301026404,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-0.448204
999998,3 Ravens Brewing,1288090456,0.234872,-0.388498,0.227290,Rauchbier,-0.404538,0.255532
999999,3 Ravens Brewing,1284360315,-0.476617,0.349704,1.062766,Rauchbier,0.350940,-0.448204

In [81]:
print(y_main)

y_main.value_counts()

0                             Hefeweizen
1                     English Strong Ale
2                 Foreign / Export Stout
3                        German Pilsener
4         American Double / Imperial IPA
                       ...
999995                           Altbier
999996                           Altbier
999997                           Altbier
999998                         Rauchbier
999999                         Rauchbier
Name: beer_style, Length: 1000000, dtype: object

American IPA                        82367
American Double / Imperial IPA      51578
American Double / Imperial Stout    39391
American Pale Ale (APA)             39151
American Porter                     33287
                                    ...
Sahti                                 315
Roggenbier                            238
Kvass                                 143
Gose                                  105
Happoshu                               87
Name: beer_style, Length: 104, dtype: int64

In [82]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [83]:
sc = StandardScaler()

In [84]:
X_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
brewery_name         999991 non-null object
review_time          1000000 non-null int64
review_overall       1000000 non-null float64
review_aroma         1000000 non-null float64
review_appearance    1000000 non-null float64
beer_style           1000000 non-null object
review_palate        1000000 non-null float64
review_taste         1000000 non-null float64
dtypes: float64(5), int64(1), object(2)
memory usage: 61.0+ MB

In [85]:
X_main[num_cols] = sc.fit_transform(X_main[num_cols])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [86]:
#ohe = OneHotEncoder(sparse=False)

In [87]:
#X_cat = pd.DataFrame(ohe.fit_transform(df_cleaned[cat_cols].replace(np.nan, 'none', regex = True)))

In [88]:
print(X_main.info())

df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
brewery_name         999991 non-null object
review_time          1000000 non-null float64
review_overall       1000000 non-null float64
review_aroma         1000000 non-null float64
review_appearance    1000000 non-null float64
beer_style           1000000 non-null object
review_palate        1000000 non-null float64
review_taste         1000000 non-null float64
dtypes: float64(6), object(2)
memory usage: 61.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 8 columns):
brewery_name         1586599 non-null object
review_time          1586614 non-null int64
review_overall       1586614 non-null float64
review_aroma         1586614 non-null float64
review_appearance    1586614 non-null float64
beer_style           1586614 non-null object
review_palate        1586614 non-null float64
review_taste         1586614 non-null float64
dtypes: float64(5), int64(1), object(2)
memory usage: 96.8+ MB

In [89]:
#ohe = OneHotEncoder(sparse=False, handle_unknown = 'ignore')

In [90]:
#categories= X_main.brewery_name.value_counts().nlargest(1000).index.tolist()

In [117]:
X_main

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,0.105230,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,Vecchio Birraio,0.119769,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,Vecchio Birraio,0.119789,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,Vecchio Birraio,0.104002,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,Caldera Brewing Company,0.885909,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...
999995,3 Ravens Brewing,1.024924,-0.476617,-1.126700,1.062766,Altbier,-0.404538,-1.151941
999996,3 Ravens Brewing,0.989668,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-1.855677
999997,3 Ravens Brewing,0.982520,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-0.448204
999998,3 Ravens Brewing,0.811114,0.234872,-0.388498,0.227290,Rauchbier,-0.404538,0.255532
999999,3 Ravens Brewing,0.761688,-0.476617,0.349704,1.062766,Rauchbier,0.350940,-0.448204

In [91]:
#ohe.fit(X_main.loc[X_main['brewery_name'].isin(categories),["brewery_name"]])

In [92]:
#brewery_names = ohe.transform(X_main[["brewery_name"]].replace(np.nan, 'none', regex = True))

In [118]:
X_main['brewery_name'].cat.codes

AttributeError: Can only use .cat accessor with a 'category' dtype

In [94]:
for category in cat_cols:
    df_cleaned[category] = X_main[category].astype('category')

In [95]:
import category_encoders as ce

In [96]:
encoder = ce.BinaryEncoder(cols=cat_cols)

In [97]:
#X_cat = pd.DataFrame(ohe.fit_transform(df_cleaned[cat_cols].replace(np.nan, 'none', regex = True)))

encoder

BinaryEncoder(cols=['brewery_name'], drop_invariant=False,
              handle_missing='value', handle_unknown='value', mapping=None,
              return_df=True, verbose=0)

In [98]:
df_binary = encoder.fit_transform(X_main)

In [99]:
df_binary

,brewery_name_0,brewery_name_1,brewery_name_2,brewery_name_3,brewery_name_4,brewery_name_5,brewery_name_6,brewery_name_7,brewery_name_8,brewery_name_9,brewery_name_10,brewery_name_11,brewery_name_12,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.105230,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,0,0,0,0,0,0,0,0,0,0,0,0,1,0.119769,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0.119789,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0.104002,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0.885909,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1,1,0,1,0,1,1,1,0,1,0,1,1.024924,-0.476617,-1.126700,1.062766,Altbier,-0.404538,-1.151941
999996,0,1,1,0,1,0,1,1,1,0,1,0,1,0.989668,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-1.855677
999997,0,1,1,0,1,0,1,1,1,0,1,0,1,0.982520,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-0.448204
999998,0,1,1,0,1,0,1,1,1,0,1,0,1,0.811114,0.234872,-0.388498,0.227290,Rauchbier,-0.404538,0.255532
999999,0,1,1,0,1,0,1,1,1,0,1,0,1,0.761688,-0.476617,0.349704,1.062766,Rauchbier,0.350940,-0.448204

In [100]:
X_main

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,0.105230,-3.322573,-2.603105,-2.279137,Hefeweizen,-3.426446,-3.263150
1,Vecchio Birraio,0.119769,-1.188106,-1.864903,-1.443661,English Strong Ale,-1.160015,-1.151941
2,Vecchio Birraio,0.119789,-1.188106,-1.864903,-1.443661,Foreign / Export Stout,-1.160015,-1.151941
3,Vecchio Birraio,0.104002,-1.188106,-1.126700,-0.608185,German Pilsener,-1.915492,-1.151941
4,Caldera Brewing Company,0.885909,0.234872,1.087906,0.227290,American Double / Imperial IPA,0.350940,0.959269
...,...,...,...,...,...,...,...,...
999995,3 Ravens Brewing,1.024924,-0.476617,-1.126700,1.062766,Altbier,-0.404538,-1.151941
999996,3 Ravens Brewing,0.989668,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-1.855677
999997,3 Ravens Brewing,0.982520,-0.476617,-0.388498,-1.443661,Altbier,0.350940,-0.448204
999998,3 Ravens Brewing,0.811114,0.234872,-0.388498,0.227290,Rauchbier,-0.404538,0.255532
999999,3 Ravens Brewing,0.761688,-0.476617,0.349704,1.062766,Rauchbier,0.350940,-0.448204

In [101]:
#df['brewery_name'].value_counts()

In [102]:
#X_main

In [103]:
#df_binary['beer_style'] = df_binary['beer_style'].to_numpy()

#df_binary['beer_style'] = df_binary['beer_style'].astype(str).astype(float)

In [104]:
#print(df_binary['beer_style'].value_counts())

In [105]:
X_train, y_train, X_val, y_val, X_test, y_test = split_sets_random(df_binary, target_col = target_col, test_ratio=0.2, to_numpy=False)

In [113]:
#X_train, y_train, X_val, y_val, X_test, y_test = split_sets_random(df_binary, target_col=target_col, test_ratio=0.2, to_numpy=True)

In [116]:
from src.models.pytorch import PytorchDataset

train_dataset = PytorchDataset(X=X_train, y=y_train)
val_dataset = PytorchDataset(X=X_val, y=y_val)
test_dataset = PytorchDataset(X=X_test, y=y_test)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [ ]:
#y_train

In [109]:
y_train

835762                    English Bitter
597938                 English Brown Ale
757221                           Witbier
982013                      American IPA
70690              Maibock / Helles Bock
                       ...
643183    American Double / Imperial IPA
765055                            Dubbel
498473               American Strong Ale
328744            American Adjunct Lager
289385            Russian Imperial Stout
Name: beer_style, Length: 600000, dtype: object

In [ ]:
#df_binary